# VirtualToPhysical
# Instance name: vm00_threadsig
# Generated: 2024-09-10T13:31:45.379962795-07:00
address_mapping_group {
  page_size: 2097152
  address_mapping {
    virtual_address: 281464337858560
    physical_address: 10485760
  }
  address_mapping {
    virtual_address: 281464329469952
    physical_address: 8388608
  }
  address_mapping {
    virtual_address: 281464346247168
    physical_address: 12582912
  }
  address_mapping {
    virtual_address: 281474899116032
    physical_address: 18874368
  }
  address_mapping {
    virtual_address: 281464321081344
    physical_address: 6291456
  }
  address_mapping {
    virtual_address: 281464350441472
    physical_address: 14680064
  }
  address_mapping {
    virtual_address: 1895825408
    physical_address: 4194304
  }
  address_mapping {
    virtual_address: 4194304
    physical_address: 2097152
  }
  address_mapping {
    virtual_address: 281472940376064
    physical_address: 16777216
  }
  information {
    page_count: 9
    bytes_mapped: 18874368
  }
}
information {
  page_count: 9
  bytes_mapped: 18874368
}
