/* **********************************************************
 * Copyright (c) 2025 Google, Inc.  All rights reserved.
 * **********************************************************/

/*
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * * Redistributions of source code must retain the above copyright notice,
 *   this list of conditions and the following disclaimer.
 *
 * * Redistributions in binary form must reproduce the above copyright notice,
 *   this list of conditions and the following disclaimer in the documentation
 *   and/or other materials provided with the distribution.
 *
 * * Neither the name of Google, Inc. nor the names of its contributors may be
 *   used to endorse or promote products derived from this software without
 *   specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL VMWARE, INC. OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
 * DAMAGE.
 */

#ifndef _NOISE_GENERATOR_H_
#define _NOISE_GENERATOR_H_ 1

#include "reader.h"
#include "../common/trace_entry.h"

namespace dynamorio {
namespace drmemtrace {

/**
 * Generates synthetic #dynamorio::drmemtrace::memref_t trace entries in a single thread
 * and presents them via an iterator interface to the scheduler.
 */
class noise_generator_t : public reader_t {
public:
    noise_generator_t();

    noise_generator_t(uint64_t num_records_to_generate);

    virtual ~noise_generator_t();

    bool
    init() override;

    std::string
    get_stream_name() const override;

protected:
    // Wraps the noise records generated by generate_trace_entry() between
    // TRACE_TYPE_THREAD, TRACE_TYPE_PID and TRACE_TYPE_THREAD_EXIT.
    virtual trace_entry_t *
    read_next_entry() override;

    // Has the main logic to generate noise records.
    virtual trace_entry_t
    generate_trace_entry();

    // This counter does not count TRACE_TYPE_THREAD or TRACE_TYPE_PID.
    // The idea is that when we want to generate at least 1 record, tid and pid have to be
    // there as well, otherwise the scheduler will report an error.
    uint64_t num_records_to_generate_ = 0;

private:
    trace_entry_t entry_ = {};
    bool marker_pid_generated_ = false;
    bool marker_tid_generated_ = false;
};

} // namespace drmemtrace
} // namespace dynamorio

#endif /* _NOISE_GENERATOR_H_ */
