/* This file was generated by codec.py from codec.txt. */

#ifndef OPCODE_NAMES_H
#define OPCODE_NAMES_H 1

const char *opcode_names[] = {
/*   0 */ "<invalid>",
/*   1 */ "<undecoded>",
/*   2 */ "<contd>",
/*   3 */ "<label>",
/*   4 */ "add",
/*   5 */ "adds",
/*   6 */ "adr",
/*   7 */ "adrp",
/*   8 */ "and",
/*   9 */ "ands",
/*  10 */ "b",
/*  11 */ "bcond",
/*  12 */ "bic",
/*  13 */ "bics",
/*  14 */ "bl",
/*  15 */ "blr",
/*  16 */ "br",
/*  17 */ "brk",
/*  18 */ "cbnz",
/*  19 */ "cbz",
/*  20 */ "eon",
/*  21 */ "eor",
/*  22 */ "ldr",
/*  23 */ "mrs",
/*  24 */ "msr",
/*  25 */ "nop",
/*  26 */ "orn",
/*  27 */ "orr",
/*  28 */ "ret",
/*  29 */ "str",
/*  30 */ "strb",
/*  31 */ "strh",
/*  32 */ "sub",
/*  33 */ "subs",
/*  34 */ "svc",
/*  35 */ "tbnz",
/*  36 */ "tbz",
          "xx",
};

#endif /* OPCODE_NAMES_H */
