/* This file was generated by codec.py from codec.txt. */

#ifndef OPCODE_NAMES_H
#define OPCODE_NAMES_H 1

const char *opcode_names[] = {
/*   0 */ "<invalid>",
/*   1 */ "<undecoded>",
/*   2 */ "<contd>",
/*   3 */ "<label>",
/*   4 */ "add",
/*   5 */ "adr",
/*   6 */ "adrp",
/*   7 */ "b",
/*   8 */ "bcond",
/*   9 */ "bl",
/*  10 */ "blr",
/*  11 */ "br",
/*  12 */ "brk",
/*  13 */ "cbnz",
/*  14 */ "cbz",
/*  15 */ "ldr",
/*  16 */ "mrs",
/*  17 */ "msr",
/*  18 */ "nop",
/*  19 */ "orr",
/*  20 */ "ret",
/*  21 */ "str",
/*  22 */ "strb",
/*  23 */ "strh",
/*  24 */ "sub",
/*  25 */ "svc",
/*  26 */ "tbnz",
/*  27 */ "tbz",
          "xx",
};

#endif /* OPCODE_NAMES_H */
