/* This file was generated by codec.py from codec.txt. */

#ifndef OPCODE_H
#define OPCODE_H 1

/* DR_API EXPORT TOFILE dr_ir_opcodes_aarch64.h */
/* DR_API EXPORT BEGIN */

/****************************************************************************
 * OPCODES
 */
/**
 * @file dr_ir_opcodes_aarch64.h
 * @brief Instruction opcode constants for AArch64.
 */
/** Opcode constants for use in the instr_t data structure. */
enum {
/*   0 */     OP_INVALID,  /* NULL, */ /**< INVALID opcode */
/*   1 */     OP_UNDECODED,  /* NULL, */ /**< UNDECODED opcode */
/*   2 */     OP_CONTD,    /* NULL, */ /**< CONTD opcode */
/*   3 */     OP_LABEL,    /* NULL, */ /**< LABEL opcode */

/*   4 */     OP_adc,             /**< AArch64 adc opcode.*/
/*   5 */     OP_adcs,            /**< AArch64 adcs opcode.*/
/*   6 */     OP_add,             /**< AArch64 add opcode.*/
/*   7 */     OP_adds,            /**< AArch64 adds opcode.*/
/*   8 */     OP_adr,             /**< AArch64 adr opcode.*/
/*   9 */     OP_adrp,            /**< AArch64 adrp opcode.*/
/*  10 */     OP_and,             /**< AArch64 and opcode.*/
/*  11 */     OP_ands,            /**< AArch64 ands opcode.*/
/*  12 */     OP_asrv,            /**< AArch64 asrv opcode.*/
/*  13 */     OP_b,               /**< AArch64 b opcode.*/
/*  14 */     OP_bcond,           /**< AArch64 bcond opcode.*/
/*  15 */     OP_bfm,             /**< AArch64 bfm opcode.*/
/*  16 */     OP_bic,             /**< AArch64 bic opcode.*/
/*  17 */     OP_bics,            /**< AArch64 bics opcode.*/
/*  18 */     OP_bl,              /**< AArch64 bl opcode.*/
/*  19 */     OP_blr,             /**< AArch64 blr opcode.*/
/*  20 */     OP_br,              /**< AArch64 br opcode.*/
/*  21 */     OP_brk,             /**< AArch64 brk opcode.*/
/*  22 */     OP_cas,             /**< AArch64 cas opcode.*/
/*  23 */     OP_casa,            /**< AArch64 casa opcode.*/
/*  24 */     OP_casab,           /**< AArch64 casab opcode.*/
/*  25 */     OP_casah,           /**< AArch64 casah opcode.*/
/*  26 */     OP_casal,           /**< AArch64 casal opcode.*/
/*  27 */     OP_casalb,          /**< AArch64 casalb opcode.*/
/*  28 */     OP_casalh,          /**< AArch64 casalh opcode.*/
/*  29 */     OP_casb,            /**< AArch64 casb opcode.*/
/*  30 */     OP_cash,            /**< AArch64 cash opcode.*/
/*  31 */     OP_casl,            /**< AArch64 casl opcode.*/
/*  32 */     OP_caslb,           /**< AArch64 caslb opcode.*/
/*  33 */     OP_caslh,           /**< AArch64 caslh opcode.*/
/*  34 */     OP_casp,            /**< AArch64 casp opcode.*/
/*  35 */     OP_caspa,           /**< AArch64 caspa opcode.*/
/*  36 */     OP_caspal,          /**< AArch64 caspal opcode.*/
/*  37 */     OP_caspl,           /**< AArch64 caspl opcode.*/
/*  38 */     OP_cbnz,            /**< AArch64 cbnz opcode.*/
/*  39 */     OP_cbz,             /**< AArch64 cbz opcode.*/
/*  40 */     OP_ccmn,            /**< AArch64 ccmn opcode.*/
/*  41 */     OP_ccmp,            /**< AArch64 ccmp opcode.*/
/*  42 */     OP_clrex,           /**< AArch64 clrex opcode.*/
/*  43 */     OP_cls,             /**< AArch64 cls opcode.*/
/*  44 */     OP_clz,             /**< AArch64 clz opcode.*/
/*  45 */     OP_crc32b,          /**< AArch64 crc32b opcode.*/
/*  46 */     OP_crc32cb,         /**< AArch64 crc32cb opcode.*/
/*  47 */     OP_crc32ch,         /**< AArch64 crc32ch opcode.*/
/*  48 */     OP_crc32cw,         /**< AArch64 crc32cw opcode.*/
/*  49 */     OP_crc32cx,         /**< AArch64 crc32cx opcode.*/
/*  50 */     OP_crc32h,          /**< AArch64 crc32h opcode.*/
/*  51 */     OP_crc32w,          /**< AArch64 crc32w opcode.*/
/*  52 */     OP_crc32x,          /**< AArch64 crc32x opcode.*/
/*  53 */     OP_csel,            /**< AArch64 csel opcode.*/
/*  54 */     OP_csinc,           /**< AArch64 csinc opcode.*/
/*  55 */     OP_csinv,           /**< AArch64 csinv opcode.*/
/*  56 */     OP_csneg,           /**< AArch64 csneg opcode.*/
/*  57 */     OP_dmb,             /**< AArch64 dmb opcode.*/
/*  58 */     OP_dsb,             /**< AArch64 dsb opcode.*/
/*  59 */     OP_eon,             /**< AArch64 eon opcode.*/
/*  60 */     OP_eor,             /**< AArch64 eor opcode.*/
/*  61 */     OP_extr,            /**< AArch64 extr opcode.*/
/*  62 */     OP_fabd,            /**< AArch64 fabd opcode.*/
/*  63 */     OP_facge,           /**< AArch64 facge opcode.*/
/*  64 */     OP_facgt,           /**< AArch64 facgt opcode.*/
/*  65 */     OP_fadd,            /**< AArch64 fadd opcode.*/
/*  66 */     OP_faddp,           /**< AArch64 faddp opcode.*/
/*  67 */     OP_fcmeq,           /**< AArch64 fcmeq opcode.*/
/*  68 */     OP_fcmge,           /**< AArch64 fcmge opcode.*/
/*  69 */     OP_fcmgt,           /**< AArch64 fcmgt opcode.*/
/*  70 */     OP_fdiv,            /**< AArch64 fdiv opcode.*/
/*  71 */     OP_fmax,            /**< AArch64 fmax opcode.*/
/*  72 */     OP_fmaxnm,          /**< AArch64 fmaxnm opcode.*/
/*  73 */     OP_fmaxnmp,         /**< AArch64 fmaxnmp opcode.*/
/*  74 */     OP_fmaxp,           /**< AArch64 fmaxp opcode.*/
/*  75 */     OP_fmin,            /**< AArch64 fmin opcode.*/
/*  76 */     OP_fminnm,          /**< AArch64 fminnm opcode.*/
/*  77 */     OP_fminnmp,         /**< AArch64 fminnmp opcode.*/
/*  78 */     OP_fminp,           /**< AArch64 fminp opcode.*/
/*  79 */     OP_fmla,            /**< AArch64 fmla opcode.*/
/*  80 */     OP_fmls,            /**< AArch64 fmls opcode.*/
/*  81 */     OP_fmul,            /**< AArch64 fmul opcode.*/
/*  82 */     OP_fmulx,           /**< AArch64 fmulx opcode.*/
/*  83 */     OP_frecps,          /**< AArch64 frecps opcode.*/
/*  84 */     OP_frsqrts,         /**< AArch64 frsqrts opcode.*/
/*  85 */     OP_fsub,            /**< AArch64 fsub opcode.*/
/*  86 */     OP_hlt,             /**< AArch64 hlt opcode.*/
/*  87 */     OP_hvc,             /**< AArch64 hvc opcode.*/
/*  88 */     OP_isb,             /**< AArch64 isb opcode.*/
/*  89 */     OP_ld1,             /**< AArch64 ld1 opcode.*/
/*  90 */     OP_ld1r,            /**< AArch64 ld1r opcode.*/
/*  91 */     OP_ld2,             /**< AArch64 ld2 opcode.*/
/*  92 */     OP_ld2r,            /**< AArch64 ld2r opcode.*/
/*  93 */     OP_ld3,             /**< AArch64 ld3 opcode.*/
/*  94 */     OP_ld3r,            /**< AArch64 ld3r opcode.*/
/*  95 */     OP_ld4,             /**< AArch64 ld4 opcode.*/
/*  96 */     OP_ld4r,            /**< AArch64 ld4r opcode.*/
/*  97 */     OP_ldadd,           /**< AArch64 ldadd opcode.*/
/*  98 */     OP_ldadda,          /**< AArch64 ldadda opcode.*/
/*  99 */     OP_ldaddab,         /**< AArch64 ldaddab opcode.*/
/* 100 */     OP_ldaddah,         /**< AArch64 ldaddah opcode.*/
/* 101 */     OP_ldaddal,         /**< AArch64 ldaddal opcode.*/
/* 102 */     OP_ldaddalb,        /**< AArch64 ldaddalb opcode.*/
/* 103 */     OP_ldaddalh,        /**< AArch64 ldaddalh opcode.*/
/* 104 */     OP_ldaddb,          /**< AArch64 ldaddb opcode.*/
/* 105 */     OP_ldaddh,          /**< AArch64 ldaddh opcode.*/
/* 106 */     OP_ldaddl,          /**< AArch64 ldaddl opcode.*/
/* 107 */     OP_ldaddlb,         /**< AArch64 ldaddlb opcode.*/
/* 108 */     OP_ldaddlh,         /**< AArch64 ldaddlh opcode.*/
/* 109 */     OP_ldar,            /**< AArch64 ldar opcode.*/
/* 110 */     OP_ldarb,           /**< AArch64 ldarb opcode.*/
/* 111 */     OP_ldarh,           /**< AArch64 ldarh opcode.*/
/* 112 */     OP_ldaxp,           /**< AArch64 ldaxp opcode.*/
/* 113 */     OP_ldaxr,           /**< AArch64 ldaxr opcode.*/
/* 114 */     OP_ldaxrb,          /**< AArch64 ldaxrb opcode.*/
/* 115 */     OP_ldaxrh,          /**< AArch64 ldaxrh opcode.*/
/* 116 */     OP_ldclr,           /**< AArch64 ldclr opcode.*/
/* 117 */     OP_ldclra,          /**< AArch64 ldclra opcode.*/
/* 118 */     OP_ldclrab,         /**< AArch64 ldclrab opcode.*/
/* 119 */     OP_ldclrah,         /**< AArch64 ldclrah opcode.*/
/* 120 */     OP_ldclral,         /**< AArch64 ldclral opcode.*/
/* 121 */     OP_ldclralb,        /**< AArch64 ldclralb opcode.*/
/* 122 */     OP_ldclralh,        /**< AArch64 ldclralh opcode.*/
/* 123 */     OP_ldclrb,          /**< AArch64 ldclrb opcode.*/
/* 124 */     OP_ldclrh,          /**< AArch64 ldclrh opcode.*/
/* 125 */     OP_ldclrl,          /**< AArch64 ldclrl opcode.*/
/* 126 */     OP_ldclrlb,         /**< AArch64 ldclrlb opcode.*/
/* 127 */     OP_ldclrlh,         /**< AArch64 ldclrlh opcode.*/
/* 128 */     OP_ldeor,           /**< AArch64 ldeor opcode.*/
/* 129 */     OP_ldeora,          /**< AArch64 ldeora opcode.*/
/* 130 */     OP_ldeorab,         /**< AArch64 ldeorab opcode.*/
/* 131 */     OP_ldeorah,         /**< AArch64 ldeorah opcode.*/
/* 132 */     OP_ldeoral,         /**< AArch64 ldeoral opcode.*/
/* 133 */     OP_ldeoralb,        /**< AArch64 ldeoralb opcode.*/
/* 134 */     OP_ldeoralh,        /**< AArch64 ldeoralh opcode.*/
/* 135 */     OP_ldeorb,          /**< AArch64 ldeorb opcode.*/
/* 136 */     OP_ldeorh,          /**< AArch64 ldeorh opcode.*/
/* 137 */     OP_ldeorl,          /**< AArch64 ldeorl opcode.*/
/* 138 */     OP_ldeorlb,         /**< AArch64 ldeorlb opcode.*/
/* 139 */     OP_ldeorlh,         /**< AArch64 ldeorlh opcode.*/
/* 140 */     OP_ldnp,            /**< AArch64 ldnp opcode.*/
/* 141 */     OP_ldp,             /**< AArch64 ldp opcode.*/
/* 142 */     OP_ldpsw,           /**< AArch64 ldpsw opcode.*/
/* 143 */     OP_ldr,             /**< AArch64 ldr opcode.*/
/* 144 */     OP_ldrb,            /**< AArch64 ldrb opcode.*/
/* 145 */     OP_ldrh,            /**< AArch64 ldrh opcode.*/
/* 146 */     OP_ldrsb,           /**< AArch64 ldrsb opcode.*/
/* 147 */     OP_ldrsh,           /**< AArch64 ldrsh opcode.*/
/* 148 */     OP_ldrsw,           /**< AArch64 ldrsw opcode.*/
/* 149 */     OP_ldset,           /**< AArch64 ldset opcode.*/
/* 150 */     OP_ldseta,          /**< AArch64 ldseta opcode.*/
/* 151 */     OP_ldsetab,         /**< AArch64 ldsetab opcode.*/
/* 152 */     OP_ldsetah,         /**< AArch64 ldsetah opcode.*/
/* 153 */     OP_ldsetal,         /**< AArch64 ldsetal opcode.*/
/* 154 */     OP_ldsetalb,        /**< AArch64 ldsetalb opcode.*/
/* 155 */     OP_ldsetalh,        /**< AArch64 ldsetalh opcode.*/
/* 156 */     OP_ldsetb,          /**< AArch64 ldsetb opcode.*/
/* 157 */     OP_ldseth,          /**< AArch64 ldseth opcode.*/
/* 158 */     OP_ldsetl,          /**< AArch64 ldsetl opcode.*/
/* 159 */     OP_ldsetlb,         /**< AArch64 ldsetlb opcode.*/
/* 160 */     OP_ldsetlh,         /**< AArch64 ldsetlh opcode.*/
/* 161 */     OP_ldsmax,          /**< AArch64 ldsmax opcode.*/
/* 162 */     OP_ldsmaxa,         /**< AArch64 ldsmaxa opcode.*/
/* 163 */     OP_ldsmaxab,        /**< AArch64 ldsmaxab opcode.*/
/* 164 */     OP_ldsmaxah,        /**< AArch64 ldsmaxah opcode.*/
/* 165 */     OP_ldsmaxal,        /**< AArch64 ldsmaxal opcode.*/
/* 166 */     OP_ldsmaxalb,       /**< AArch64 ldsmaxalb opcode.*/
/* 167 */     OP_ldsmaxalh,       /**< AArch64 ldsmaxalh opcode.*/
/* 168 */     OP_ldsmaxb,         /**< AArch64 ldsmaxb opcode.*/
/* 169 */     OP_ldsmaxh,         /**< AArch64 ldsmaxh opcode.*/
/* 170 */     OP_ldsmaxl,         /**< AArch64 ldsmaxl opcode.*/
/* 171 */     OP_ldsmaxlb,        /**< AArch64 ldsmaxlb opcode.*/
/* 172 */     OP_ldsmaxlh,        /**< AArch64 ldsmaxlh opcode.*/
/* 173 */     OP_ldsmin,          /**< AArch64 ldsmin opcode.*/
/* 174 */     OP_ldsmina,         /**< AArch64 ldsmina opcode.*/
/* 175 */     OP_ldsminab,        /**< AArch64 ldsminab opcode.*/
/* 176 */     OP_ldsminah,        /**< AArch64 ldsminah opcode.*/
/* 177 */     OP_ldsminal,        /**< AArch64 ldsminal opcode.*/
/* 178 */     OP_ldsminalb,       /**< AArch64 ldsminalb opcode.*/
/* 179 */     OP_ldsminalh,       /**< AArch64 ldsminalh opcode.*/
/* 180 */     OP_ldsminb,         /**< AArch64 ldsminb opcode.*/
/* 181 */     OP_ldsminh,         /**< AArch64 ldsminh opcode.*/
/* 182 */     OP_ldsminl,         /**< AArch64 ldsminl opcode.*/
/* 183 */     OP_ldsminlb,        /**< AArch64 ldsminlb opcode.*/
/* 184 */     OP_ldsminlh,        /**< AArch64 ldsminlh opcode.*/
/* 185 */     OP_ldtr,            /**< AArch64 ldtr opcode.*/
/* 186 */     OP_ldtrb,           /**< AArch64 ldtrb opcode.*/
/* 187 */     OP_ldtrh,           /**< AArch64 ldtrh opcode.*/
/* 188 */     OP_ldtrsb,          /**< AArch64 ldtrsb opcode.*/
/* 189 */     OP_ldtrsh,          /**< AArch64 ldtrsh opcode.*/
/* 190 */     OP_ldtrsw,          /**< AArch64 ldtrsw opcode.*/
/* 191 */     OP_ldumax,          /**< AArch64 ldumax opcode.*/
/* 192 */     OP_ldumaxa,         /**< AArch64 ldumaxa opcode.*/
/* 193 */     OP_ldumaxab,        /**< AArch64 ldumaxab opcode.*/
/* 194 */     OP_ldumaxah,        /**< AArch64 ldumaxah opcode.*/
/* 195 */     OP_ldumaxal,        /**< AArch64 ldumaxal opcode.*/
/* 196 */     OP_ldumaxalb,       /**< AArch64 ldumaxalb opcode.*/
/* 197 */     OP_ldumaxalh,       /**< AArch64 ldumaxalh opcode.*/
/* 198 */     OP_ldumaxb,         /**< AArch64 ldumaxb opcode.*/
/* 199 */     OP_ldumaxh,         /**< AArch64 ldumaxh opcode.*/
/* 200 */     OP_ldumaxl,         /**< AArch64 ldumaxl opcode.*/
/* 201 */     OP_ldumaxlb,        /**< AArch64 ldumaxlb opcode.*/
/* 202 */     OP_ldumaxlh,        /**< AArch64 ldumaxlh opcode.*/
/* 203 */     OP_ldumin,          /**< AArch64 ldumin opcode.*/
/* 204 */     OP_ldumina,         /**< AArch64 ldumina opcode.*/
/* 205 */     OP_lduminab,        /**< AArch64 lduminab opcode.*/
/* 206 */     OP_lduminah,        /**< AArch64 lduminah opcode.*/
/* 207 */     OP_lduminal,        /**< AArch64 lduminal opcode.*/
/* 208 */     OP_lduminalb,       /**< AArch64 lduminalb opcode.*/
/* 209 */     OP_lduminalh,       /**< AArch64 lduminalh opcode.*/
/* 210 */     OP_lduminb,         /**< AArch64 lduminb opcode.*/
/* 211 */     OP_lduminh,         /**< AArch64 lduminh opcode.*/
/* 212 */     OP_lduminl,         /**< AArch64 lduminl opcode.*/
/* 213 */     OP_lduminlb,        /**< AArch64 lduminlb opcode.*/
/* 214 */     OP_lduminlh,        /**< AArch64 lduminlh opcode.*/
/* 215 */     OP_ldur,            /**< AArch64 ldur opcode.*/
/* 216 */     OP_ldurb,           /**< AArch64 ldurb opcode.*/
/* 217 */     OP_ldurh,           /**< AArch64 ldurh opcode.*/
/* 218 */     OP_ldursb,          /**< AArch64 ldursb opcode.*/
/* 219 */     OP_ldursh,          /**< AArch64 ldursh opcode.*/
/* 220 */     OP_ldursw,          /**< AArch64 ldursw opcode.*/
/* 221 */     OP_ldxp,            /**< AArch64 ldxp opcode.*/
/* 222 */     OP_ldxr,            /**< AArch64 ldxr opcode.*/
/* 223 */     OP_ldxrb,           /**< AArch64 ldxrb opcode.*/
/* 224 */     OP_ldxrh,           /**< AArch64 ldxrh opcode.*/
/* 225 */     OP_lslv,            /**< AArch64 lslv opcode.*/
/* 226 */     OP_lsrv,            /**< AArch64 lsrv opcode.*/
/* 227 */     OP_madd,            /**< AArch64 madd opcode.*/
/* 228 */     OP_movk,            /**< AArch64 movk opcode.*/
/* 229 */     OP_movn,            /**< AArch64 movn opcode.*/
/* 230 */     OP_movz,            /**< AArch64 movz opcode.*/
/* 231 */     OP_mrs,             /**< AArch64 mrs opcode.*/
/* 232 */     OP_msr,             /**< AArch64 msr opcode.*/
/* 233 */     OP_msub,            /**< AArch64 msub opcode.*/
/* 234 */     OP_nop,             /**< AArch64 nop opcode.*/
/* 235 */     OP_orn,             /**< AArch64 orn opcode.*/
/* 236 */     OP_orr,             /**< AArch64 orr opcode.*/
/* 237 */     OP_prfm,            /**< AArch64 prfm opcode.*/
/* 238 */     OP_prfum,           /**< AArch64 prfum opcode.*/
/* 239 */     OP_rbit,            /**< AArch64 rbit opcode.*/
/* 240 */     OP_ret,             /**< AArch64 ret opcode.*/
/* 241 */     OP_rev,             /**< AArch64 rev opcode.*/
/* 242 */     OP_rev16,           /**< AArch64 rev16 opcode.*/
/* 243 */     OP_rev32,           /**< AArch64 rev32 opcode.*/
/* 244 */     OP_rorv,            /**< AArch64 rorv opcode.*/
/* 245 */     OP_sbc,             /**< AArch64 sbc opcode.*/
/* 246 */     OP_sbcs,            /**< AArch64 sbcs opcode.*/
/* 247 */     OP_sbfm,            /**< AArch64 sbfm opcode.*/
/* 248 */     OP_sdiv,            /**< AArch64 sdiv opcode.*/
/* 249 */     OP_sev,             /**< AArch64 sev opcode.*/
/* 250 */     OP_sevl,            /**< AArch64 sevl opcode.*/
/* 251 */     OP_smaddl,          /**< AArch64 smaddl opcode.*/
/* 252 */     OP_smc,             /**< AArch64 smc opcode.*/
/* 253 */     OP_smsubl,          /**< AArch64 smsubl opcode.*/
/* 254 */     OP_smulh,           /**< AArch64 smulh opcode.*/
/* 255 */     OP_st1,             /**< AArch64 st1 opcode.*/
/* 256 */     OP_st2,             /**< AArch64 st2 opcode.*/
/* 257 */     OP_st3,             /**< AArch64 st3 opcode.*/
/* 258 */     OP_st4,             /**< AArch64 st4 opcode.*/
/* 259 */     OP_stlr,            /**< AArch64 stlr opcode.*/
/* 260 */     OP_stlrb,           /**< AArch64 stlrb opcode.*/
/* 261 */     OP_stlrh,           /**< AArch64 stlrh opcode.*/
/* 262 */     OP_stlxp,           /**< AArch64 stlxp opcode.*/
/* 263 */     OP_stlxr,           /**< AArch64 stlxr opcode.*/
/* 264 */     OP_stlxrb,          /**< AArch64 stlxrb opcode.*/
/* 265 */     OP_stlxrh,          /**< AArch64 stlxrh opcode.*/
/* 266 */     OP_stnp,            /**< AArch64 stnp opcode.*/
/* 267 */     OP_stp,             /**< AArch64 stp opcode.*/
/* 268 */     OP_str,             /**< AArch64 str opcode.*/
/* 269 */     OP_strb,            /**< AArch64 strb opcode.*/
/* 270 */     OP_strh,            /**< AArch64 strh opcode.*/
/* 271 */     OP_sttr,            /**< AArch64 sttr opcode.*/
/* 272 */     OP_sttrb,           /**< AArch64 sttrb opcode.*/
/* 273 */     OP_sttrh,           /**< AArch64 sttrh opcode.*/
/* 274 */     OP_stur,            /**< AArch64 stur opcode.*/
/* 275 */     OP_sturb,           /**< AArch64 sturb opcode.*/
/* 276 */     OP_sturh,           /**< AArch64 sturh opcode.*/
/* 277 */     OP_stxp,            /**< AArch64 stxp opcode.*/
/* 278 */     OP_stxr,            /**< AArch64 stxr opcode.*/
/* 279 */     OP_stxrb,           /**< AArch64 stxrb opcode.*/
/* 280 */     OP_stxrh,           /**< AArch64 stxrh opcode.*/
/* 281 */     OP_sub,             /**< AArch64 sub opcode.*/
/* 282 */     OP_subs,            /**< AArch64 subs opcode.*/
/* 283 */     OP_svc,             /**< AArch64 svc opcode.*/
/* 284 */     OP_swp,             /**< AArch64 swp opcode.*/
/* 285 */     OP_swpa,            /**< AArch64 swpa opcode.*/
/* 286 */     OP_swpab,           /**< AArch64 swpab opcode.*/
/* 287 */     OP_swpah,           /**< AArch64 swpah opcode.*/
/* 288 */     OP_swpal,           /**< AArch64 swpal opcode.*/
/* 289 */     OP_swpalb,          /**< AArch64 swpalb opcode.*/
/* 290 */     OP_swpalh,          /**< AArch64 swpalh opcode.*/
/* 291 */     OP_swpb,            /**< AArch64 swpb opcode.*/
/* 292 */     OP_swph,            /**< AArch64 swph opcode.*/
/* 293 */     OP_swpl,            /**< AArch64 swpl opcode.*/
/* 294 */     OP_swplb,           /**< AArch64 swplb opcode.*/
/* 295 */     OP_swplh,           /**< AArch64 swplh opcode.*/
/* 296 */     OP_sys,             /**< AArch64 sys opcode.*/
/* 297 */     OP_tbnz,            /**< AArch64 tbnz opcode.*/
/* 298 */     OP_tbz,             /**< AArch64 tbz opcode.*/
/* 299 */     OP_ubfm,            /**< AArch64 ubfm opcode.*/
/* 300 */     OP_udiv,            /**< AArch64 udiv opcode.*/
/* 301 */     OP_umaddl,          /**< AArch64 umaddl opcode.*/
/* 302 */     OP_umsubl,          /**< AArch64 umsubl opcode.*/
/* 303 */     OP_umulh,           /**< AArch64 umulh opcode.*/
/* 304 */     OP_wfe,             /**< AArch64 wfe opcode.*/
/* 305 */     OP_wfi,             /**< AArch64 wfi opcode.*/
/* 306 */     OP_yield,           /**< AArch64 yield opcode.*/

    OP_ldstex, /* single-entry single-exit block with exclusive load/store */
    OP_xx, /* placeholder for undecoded instructions */

    OP_AFTER_LAST,
    OP_FIRST = OP_LABEL + 1,      /**< First real opcode. */
    OP_LAST  = OP_AFTER_LAST - 1, /**< Last real opcode. */
};

/* alternative names */
#define OP_jmp       OP_b      /**< Platform-independent opcode name for jump. */
#define OP_jmp_short OP_b      /**< Platform-independent opcode name for short jump. */
#define OP_load      OP_ldr    /**< Platform-independent opcode name for load. */
#define OP_store     OP_str    /**< Platform-independent opcode name for store. */

/****************************************************************************/
/* DR_API EXPORT END */

#endif /* OPCODE_H */
