#!/usr/bin/tclsh
# **********************************************************
# Copyright (c) 2017-2023 Google, Inc.    All rights reserved.
# **********************************************************

# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# * Redistributions of source code must retain the above copyright notice,
#   this list of conditions and the following disclaimer.
#
# * Redistributions in binary form must reproduce the above copyright notice,
#   this list of conditions and the following disclaimer in the documentation
#   and/or other materials provided with the distribution.
#
# * Neither the name of Google, Inc. nor the names of its contributors may be
#   used to endorse or promote products derived from this software without
#   specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL VMWARE, INC. OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
# OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
# DAMAGE.

##################################################
# Exclusions for *all* code style checks:

# XXX: even recent Ubuntu (i.e., including Travis) is still packaging
# vera++ 1.2.1 which uses an older exclusion syntax that does not
# support regular expressions.  Thus we use the older syntax here for the files
# that are easy to list, but for excluding whole dirs we use regex checks
# inside our own third_party/vera++/use_vera++.cmake.

set rules {
    line_length_content
    multi_line_body
    break_after_return_type
    no_space_after_control
    space_after_call
    required_namespaces
}

# TODO i#7303: Remove drmf and drsyscall files when formatting errrors
# are fixed.
set drsyscall_files {
    utils.h asm_utils_arm.asm asm_utils_x86.asm asm_utils.h windefs.h
    utils_shared.c sysnum_linux.h utils.c drmf_utils.c samples drmf.h
    version.c public.h strace.c ntktm.h ntwow64.h ndk_iotypes.h ntmmapi.h
    safdlib.h tls.h ntioapi.h ntgdi.h ntpsapi.h tcpioctl.h afd_shared.h
    ntalpc.h ntobapi.h ntregapi.h ntuser.h ktmtypes.h kernel32_private.h
    ntgdityp.h ndk_extypes.h ntifs.h ntalpctyp.h winnt_recent.h ndk_psfuncs.h
    ntddk.h ndk_dbgktypes.h wsock.h ntseapi.h ntmisc.h ntpnpapi.h wdm.h
    ntuser_win8.h ntkeapi.h winioctl.h iptypes_undocumented.h ntexapi.h
    ndk_lpctypes.h ndk_mmtypes.h dxsdk crtdbg.h ntuser_ex.h psdk ndk_ketypes.h
    tdi.h ntgdihdl.h d3dcaps.h ntgdi.h dxgiformat.h dvp.h d3dnthal.h ddrawint.h
    prntfont.h d3dtypes.h ddraw.h winddi.h drsyscall_os.h
    table_windows_ntoskrnl.c drsyscall.c mksystable.pl drsyscall.h
    drsyscall_usercallx.h drsyscall_linux.c linux_defines.h drsyscall_driver.c
    table_linux_ioctl.c drsyscall_macos.c table_defines.h table_windows_ntuser.c
    drsyscall_fileparse.c pdb2sysfile.cpp drsyscall_wingdi.c
    table_windows_kernel32.c drsyscall_numx.h table_windows_ntusercall.c
    table_linux.c drsyscall.dox drsyscall_driver.h table_windows_ntgdi.c
    drsyscall_windows.c drsyscall_windows.h table_macos_bsd.c
    table_windows_ntoskrnl_infoclass.c
}

foreach rule $rules {
    set ruleExclusions($rule) {
        # Don't complain about the test file during the build.
        style_test.c
        # Rarely-used files consisting of very old code which we
        # should probably just remove is exempted as it's not worth
        # the time to clean up right now.
        vista_hash.c
        optimize.c
        loadtoconst.c
        loadtoconst.h
        retcheck.c
        sideline.c
        symtab.c
        # tools/* in this category is excluded via regex.
    }
    # TODO i#7303: Remove drmf and drsyscall files when formatting errrors
    # are fixed.
    foreach drsyscall_file $drsyscall_files {
        lappend ruleExclusions($rule) [file tail $drsyscall_file]
    }
}

## 1.3.0 syntax for reference:
##
## # Third-party files we do not plan to change.
## .*/third_party/.*
##
## # Don't complain about the test file during the build.
## .*/make/style_checks/.*
##
## # Rarely-used files consisting of very old code which we should probably just remove
## # is exempted as it's not worth the time to clean up right now.
## .*/clients/standalone/vista_hash.c
## .*/core/arch/x86/optimize.c
## .*/core/arch/loadtoconst.*
## .*/core/arch/retcheck.c
## .*/core/arch/sideline.c
## .*/core/unix/symtab.c
## .*/tools/.*
##
## # XXX i#2369: these have not yet been cleaned up but we plan to enable here
## # at some point.
## .*/suite/tests/.*
## .*/libutil/.*
