#!/usr/bin/perl

# **********************************************************
# Copyright (c) 2001 VMware, Inc.  All rights reserved.
# **********************************************************

# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# * Redistributions of source code must retain the above copyright notice,
#   this list of conditions and the following disclaimer.
#
# * Redistributions in binary form must reproduce the above copyright notice,
#   this list of conditions and the following disclaimer in the documentation
#   and/or other materials provided with the distribution.
#
# * Neither the name of VMware, Inc. nor the names of its contributors may be
#   used to endorse or promote products derived from this software without
#   specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL VMWARE, INC. OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
# OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
# DAMAGE.

### RunInPar
### Runs shell commands in a text file in parallel
### author: Derek Bruening   April 2001
###
### Must place "-SPLIT" on its own line to separate processors' work

$usage = "Usage: $0 <file>\n";
if ($#ARGV < 0) {
    print $usage;
    exit;
}
$infile = shift;

$proc = 0;
$line = 0;
open(IN, "< $infile") || die "Error: Couldn't open $infile for input\n";
open(OUT, "> .#mp-$proc") || die "Error in opening output file\n";
while (<IN>) {
    next if /^\#/;
    next if /^$/;
    if ($_ =~ /^-SPLIT$/) {
        close(OUT);
        $proc++;
        open(OUT, "> .#mp-$proc") || die "Error in opening output file\n";
    } else {
        print OUT $_;
    }
}
close(IN);
close(OUT);

@subs = `ls .#mp-*`;
foreach $f (@subs) {
    chop $f; # this affects @subs, only do it once!
    unless (fork()) {
        exec("/bin/csh -s < $f");
        exit(0);
    }
}
foreach $f (@subs) {
    wait;
}

# clean up
system("rm .#mp-*");
