name: ci-aarch64-native

on:
  push:
    branches:
      - DEBUGINFRA-315

  workflow_dispatch:

jobs:
  Explore-GitHub-Actions:
    runs-on: [self-hosted, linux, ARM64]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          submodules: true

      # We also need origin/master for pre-commit source file checks in runsuite.cmake.
      # But fetching multiple branches isn't supported yet: actions/checkout#214
      # Pending PR that adds this support actions/checkout#155
      # TODO i#4549: When necessary support is available, remove/replace the
      # workaround here and from every job in other Github Actions CI workflows.
      - name: Fetch master
        run: git fetch --no-tags --depth=1 origin master

      - name: Create build directory
        working-directory: ${{ github.workspace }}
        run: mkdir build

      - name: Run Suite
        working-directory: ${{ github.workspace }}/build
        run: ../suite/runsuite_wrapper.pl travis

