# **********************************************************
# Copyright (c) 2020 Google, Inc.  All rights reserved.
# **********************************************************

# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# * Redistributions of source code must retain the above copyright notice,
#   this list of conditions and the following disclaimer.
#
# * Redistributions in binary form must reproduce the above copyright notice,
#   this list of conditions and the following disclaimer in the documentation
#   and/or other materials provided with the distribution.
#
# * Neither the name of Google, Inc. nor the names of its contributors may be
#   used to endorse or promote products derived from this software without
#   specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL VMWARE, INC. OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
# OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
# DAMAGE.

# Github Actions workflow for Continuous Integration testing on Linux and MacOS.

name: ci-test-suites
on:
  # Run on pushes to any repository branch.
  push:

  # Manual trigger using the Actions page. May remove when integration complete.
  workflow_dispatch:

defaults:
  run:
    shell: bash
  # We'd like to add common initial steps for all jobs, but that's not supported.
  # Composite Run Steps can help, but we don't have that many common steps -- just
  # checkout and fetch for now.
  # https://docs.github.com/en/free-pro-team@latest/actions/creating-actions/about-actions#composite-run-steps-actions
  # https://github.community/t/reusing-sharing-inheriting-steps-between-jobs-declarations

jobs:
  # 32-bit Linux build with gcc and run tests:
  x86:
    runs-on: ubuntu-16.04

    # When checking out the repository that triggered a workflow, actions/checkout@v2
    # defaults to the reference or SHA for that event. See documentation for ref at
    # https://github.com/actions/checkout
    steps:
    - uses: actions/checkout@v2

    # We also need origin/master for pre-commit source file checks in runsuite.cmake.
    # But fetching multiple branches isn't supported yet: actions/checkout#214
    # Pending PR that adds this support actions/checkout#155
    # TODO i#4549: Remove/replace this workaround when necessary support is added.
    - run: git fetch --no-tags --depth=1 origin master

    # Install multilib for non-cross-compiling Linux build:
    - name: Create Build Environment
      run: |
        sudo apt-get -y install doxygen vera++ cmake zlib1g-dev libsnappy-dev \
          g++-multilib

    - name: Run Suite
      working-directory: ${{ github.workspace }}
      run: ./suite/runsuite_wrapper.pl travis 32_only
      env:
        DYNAMORIO_CROSS_AARCHXX_LINUX_ONLY: no

  # 64-bit Linux build with gcc and run tests:
  x86-64:
    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@v2

    - run: git fetch --no-tags --depth=1 origin master

    # Install multilib for non-cross-compiling Linux build:
    - name: Create Build Environment
      run: |
        sudo apt-get -y install doxygen vera++ cmake zlib1g-dev libsnappy-dev \
          g++-multilib

    - name: Run Suite
      working-directory: ${{ github.workspace }}
      run: ./suite/runsuite_wrapper.pl travis 64_only
      env:
        DYNAMORIO_CROSS_AARCHXX_LINUX_ONLY: no

    - name: Send failure mail
      if: failure()
      uses: dawidd6/action-send-mail@v2
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{secrets.MAIL_USERNAME}}
        password: ${{secrets.MAIL_PASSWORD}}
        subject: Github Actions CI FAILED on ${{github.repository}} ${{github.ref}}
        # Literal body:
        body: |
          Github Actions CI workflow run FAILED!

          Workflow: ${{github.workflow}}/x86-64
          Repository: ${{github.repository}}
          Branch ref: ${{github.ref}}
          SHA: ${{github.sha}}
          Triggering actor: ${{github.actor}}
          Triggering event: ${{github.event_name}}
          Run Id: ${{github.run_id}}

          See more details on github.com/abhinav92003/dynamorio/actions/runs/${{github.run_id}}

        to: sharmaabhinav@google.com
        from: Github Action CI


  # AArchXX cross-compile with gcc, no tests:
  aarchxx-cross-compile:
    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@v2

    - run: git fetch --no-tags --depth=1 origin master

    # Install cross-compilers for cross-compiling Linux build:
    - name: Create Build Environment
      run: |
        sudo apt-get -y install doxygen vera++ cmake zlib1g-dev libsnappy-dev \
          g++-arm-linux-gnueabihf g++-aarch64-linux-gnu

    - name: Run Suite
      working-directory: ${{ github.workspace }}
      run: ./suite/runsuite_wrapper.pl travis
      env:
        DYNAMORIO_CROSS_AARCHXX_LINUX_ONLY: yes

    - name: Send failure mail
      if: failure()
      uses: dawidd6/action-send-mail@v2
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{secrets.MAIL_USERNAME}}
        password: ${{secrets.MAIL_PASSWORD}}
        subject: Github Actions CI FAILED on ${{github.repository}} ${{github.ref}}
        # Literal body:
        body: |
          Github Actions CI workflow run FAILED!

          Workflow: ${{github.workflow}}/aarchxx-cross-compile
          Repository: ${{github.repository}}
          Branch ref: ${{github.ref}}
          SHA: ${{github.sha}}
          Triggering actor: ${{github.actor}}
          Triggering event: ${{github.event_name}}
          Run Id: ${{github.run_id}}

          See more details on github.com/abhinav92003/dynamorio/actions/runs/${{github.run_id}}

        to: sharmaabhinav@google.com
        from: Github Action CI


  # Android ARM cross-compile with gcc, no tests:
  android-arm-cross-compile:
    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@v2

    - run: git fetch --no-tags --depth=1 origin master

    # Fetch and install Android NDK for Andoid cross-compile build.
    - name: Create Build Environment
      run: |
        sudo apt-get -y install doxygen vera++ cmake zlib1g-dev libsnappy-dev
        cd /tmp
        wget https://dl.google.com/android/repository/android-ndk-r10e-linux-x86_64.zip
        unzip -q android-ndk-r10e-linux-x86_64.zip
        android-ndk-r10e/build/tools/make-standalone-toolchain.sh --arch=arm \
          --toolchain=arm-linux-androideabi-4.9 --platform=android-21 \
          --install-dir=/tmp/android-gcc-arm-ndk-10e
        # Manually force using ld.bfd, setting CMAKE_LINKER does not work.
        ln -sf ld.bfd /tmp/android-gcc-arm-ndk-10e/arm-linux-androideabi/bin/ld
        ln -sf arm-linux-androideabi-ld.bfd \
          /tmp/android-gcc-arm-ndk-10e/bin/arm-linux-androideabi-ld

    - name: Run Suite
      working-directory: ${{ github.workspace }}
      env:
        DYNAMORIO_CROSS_ANDROID_ONLY: yes
        DYNAMORIO_ANDROID_TOOLCHAIN: /tmp/android-gcc-arm-ndk-10e
      run: ./suite/runsuite_wrapper.pl travis

    - name: Send failure mail
      if: failure()
      uses: dawidd6/action-send-mail@v2
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{secrets.MAIL_USERNAME}}
        password: ${{secrets.MAIL_PASSWORD}}
        subject: Github Actions CI FAILED on ${{github.repository}} ${{github.ref}}
        # Literal body:
        body: |
          Github Actions CI workflow run FAILED!

          Workflow: ${{github.workflow}}/android-arm-cross-compile
          Repository: ${{github.repository}}
          Branch ref: ${{github.ref}}
          SHA: ${{github.sha}}
          Triggering actor: ${{github.actor}}
          Triggering event: ${{github.event_name}}
          Run Id: ${{github.run_id}}

          See more details on github.com/abhinav92003/dynamorio/actions/runs/${{github.run_id}}

        to: sharmaabhinav@google.com
        from: Github Action CI


  # 64-bit Linux build with clang, no tests (runsuite.cmake disables the tests),
  # install and require clang-format.
  # We used to build 32-bit with clang but have decided that is not worth
  # the Travis resources: 64-bit hits most clang-only warnings and 64-bit
  # is the primary target these days.
  clang-format:
    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@v2

    - run: git fetch --no-tags --depth=1 origin master

    # Install multilib for non-cross-compiling Linux build:
    - name: Create Build Environment
      run: |
        sudo apt-get -y install doxygen vera++ cmake zlib1g-dev libsnappy-dev \
          g++-multilib

    - name: Run Suite
      working-directory: ${{ github.workspace }}
      run: ./suite/runsuite_wrapper.pl travis 64_only require_format
      env:
        DYNAMORIO_CROSS_AARCHXX_LINUX_ONLY: no
        CC: clang-9
        CXX: clang++-9

    - name: Send failure mail
      if: failure()
      uses: dawidd6/action-send-mail@v2
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{secrets.MAIL_USERNAME}}
        password: ${{secrets.MAIL_PASSWORD}}
        subject: Github Actions CI FAILED on ${{github.repository}} ${{github.ref}}
        # Literal body:
        body: |
          Github Actions CI workflow run FAILED!

          Workflow: ${{github.workflow}}/clang-format
          Repository: ${{github.repository}}
          Branch ref: ${{github.ref}}
          SHA: ${{github.sha}}
          Triggering actor: ${{github.actor}}
          Triggering event: ${{github.event_name}}
          Run Id: ${{github.run_id}}

          See more details on github.com/abhinav92003/dynamorio/actions/runs/${{github.run_id}}

        to: sharmaabhinav@google.com
        from: Github Action CI

  # 64-bit OSX build with clang and run tests:
  osx-64bit:
    runs-on: macos-10.15

    steps:
    - uses: actions/checkout@v2

    - run: git fetch --no-tags --depth=1 origin master

    - name: Create Build Environment
      run: |
        brew install nasm

    - name: Run Suite
      working-directory: ${{ github.workspace }}
      run: ./suite/runsuite_wrapper.pl travis 64_only
      env:
        DYNAMORIO_CROSS_AARCHXX_LINUX_ONLY: no
        # Change xcode version for current session:
        # https://www.unix.com/man-page/osx/1/xcode-select/
        # https://github.community/t/selecting-an-xcode-version/16204/3
        # To find available versions, add the following as a step above:
        #  - run: ls -l /Applications
        DEVELOPER_DIR: /Applications/Xcode_11.3.1.app/Contents/Developer

    - name: Send failure mail
      if: failure()
      uses: dawidd6/action-send-mail@v2
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{secrets.MAIL_USERNAME}}
        password: ${{secrets.MAIL_PASSWORD}}
        subject: Github Actions CI FAILED on ${{github.repository}} ${{github.ref}}
        # Literal body:
        body: |
          Github Actions CI workflow run FAILED!

          Workflow: ${{github.workflow}}/osx-64bit
          Repository: ${{github.repository}}
          Branch ref: ${{github.ref}}
          SHA: ${{github.sha}}
          Triggering actor: ${{github.actor}}
          Triggering event: ${{github.event_name}}
          Run Id: ${{github.run_id}}

          See more details on github.com/abhinav92003/dynamorio/actions/runs/${{github.run_id}}

        to: sharmaabhinav@google.com
        from: Github Action CI

  # AArch64 drdecode and drmemtrace on x86:
  a64-on-x86:
    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@v2

    - run: git fetch --no-tags --depth=1 origin master

    - name: Create Build Environment
      run: |
        sudo apt-get -y install doxygen vera++ cmake zlib1g-dev libsnappy-dev

    - name: Run Suite
      working-directory: ${{ github.workspace }}
      run: ./suite/runsuite_wrapper.pl travis
      env:
        DYNAMORIO_A64_ON_X86_ONLY: yes

    - name: Send failure mail
      if: failure()
      uses: dawidd6/action-send-mail@v2
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{secrets.MAIL_USERNAME}}
        password: ${{secrets.MAIL_PASSWORD}}
        subject: Github Actions CI FAILED on ${{github.repository}} ${{github.ref}}
        # Literal body:
        body: |
          Github Actions CI workflow run FAILED!

          Workflow: ${{github.workflow}}/a64-on-x86
          Repository: ${{github.repository}}
          Branch ref: ${{github.ref}}
          SHA: ${{github.sha}}
          Triggering actor: ${{github.actor}}
          Triggering event: ${{github.event_name}}
          Run Id: ${{github.run_id}}

          See more details on github.com/abhinav92003/dynamorio/actions/runs/${{github.run_id}}

        to: sharmaabhinav@google.com
        from: Github Action CI
