name: ci-linux
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [opened, edited]

jobs:
  linux-32bit:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Create Build Environment
      # Some projects don't allow in-source building, so create a separate build directory
      # We'll use this as our working directory for all subsequent commands
      run: sudo apt-get -y install g++-multilib; cmake -E make_directory ${{runner.workspace}}/build
        
    - name: RunSuite
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: suite/runsuite_wrapper.pl github-action $EXTRA_ARGS
      env:
        DYNAMORIO_CROSS_AARCHXX_LINUX_ONLY: no
        DEPLOY: no
        EXTRA_ARGS: "32_only"

