name: ci-notif
on:
  # Run on pushes to any repository branch.
  push:

  # Manual trigger using the Actions page. May remove when integration complete.
  workflow_dispatch:

defaults:
  run:
    shell: bash
  # We'd like to add common initial steps for all jobs, but that's not supported.
  # Composite Run Steps can help, but we don't have that many common steps -- just
  # checkout and fetch for now.
  # https://docs.github.com/en/free-pro-team@latest/actions/creating-actions/about-actions#composite-run-steps-actions
  # https://github.community/t/reusing-sharing-inheriting-steps-between-jobs-declarations

jobs:
  job_id:
    runs-on: ubuntu-latest
    steps:
    - name: Failing step
      run: |
        exit 1
    - name: Send mail
      if: failure()
      uses: dawidd6/action-send-mail@v2
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{secrets.MAIL_USERNAME}}
        password: ${{secrets.MAIL_PASSWORD}}
        subject: |
          [${{github.repository}}] Github Actions ${{github.workflow}} FAILED 
          on ${{github.event_name}} at ${{github.ref}}
        # Literal body:
        body: |
          Build job of ${{github.repository}} Failed! workflow repository- ${{github.repository}} action ${{github.action}} 
          actor ${{github.actor}} base ref ${{github.base_ref}} head ref ${{github.head_ref}} ref ${{github.ref}} run-id ${{github.run_id}} workflow ${{github.workflow}} number ${{github.run_number}}
          
          Github Actions CI triggered by ${{github.actor}} on repository ${{github.repository}}/${{github.base_ref}} (${{github.sha}}) Failed!
          github.com/abhinav92003/dynamorio/actions/runs/${{github.run_id}}
          
        # Read file contents as body:
        # body: file://README.md
        to: sharmaabhinav@google.com
        from: Github action 
